spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test
    initialize: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  redis:
    host: 192.168.99.100
    port: 6379
