spring:
  social:
    facebook:
      app-id: ${facebook.app-id}
      app-secret: ${facebook.app-secret}
    twitter:
      app-id: ${twitter.app-id}
      app-secret: ${twitter.app-secret}
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test
    username: test-user
    password: test-password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
